apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: portfolio
  labels:
    app: portfolio-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-site
  template:
    metadata:
      labels:
        app: portfolio-site
    spec:
      containers:
      - name: portfolio-site
        image: docker.io/shivanivaru10/portfolio-site:latest
        ports:
        - containerPort: 80
